name: Deploy Django to GCP

on:
  push:
    branches: [main]
    paths:
      - 'django_app/**'
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Auth Docker to Artifact Registry
      run: |
        gcloud auth configure-docker REGION-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE="REGION-docker.pkg.dev/PROJECT_ID/repo/django:$(date +%s)"
        docker build -t $IMAGE ./django_app
        docker push $IMAGE
        echo "IMAGE_TAG=$IMAGE" >> $GITHUB_ENV

    - name: Apply Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"
